CC-10: created edit/delete projectID page
Banyan-Labs/casestudy-cms pull request #10
Opened 2021-09-02 19:41 UTC by StephanieKirshner

2021-09-02 21:02 UTC, StephanieKirshner commented
![projectIdBottom](https://user-images.githubusercontent.com/88007877/131915598-a1274a3d-5f4e-4625-9606-b0310c4e8b7e.png)
![projectIdTop](https://user-images.githubusercontent.com/88007877/131915628-9d4be6ad-3d86-48a4-8dc6-9cad6b46ba70.png)

2021-09-02 21:31 UTC, jdickerson-banyan requested changes
I left 2 comments, but only one requires a change

2021-09-02 21:31 UTC, jdickerson-banyan commented on src/components/EditDelete/EditDelete.jsx
> +import './style.js';
This line is not necessary with styled components

2021-09-02 21:31 UTC, jdickerson-banyan commented on src/App.js
> +      <EditDelete />
You did not need to make changes to this file for your ticket. Don't bother changing it because I am going to make changes to this file myself. However, it is fine to change this file in order to render your code, but you should not commit this change.

2021-09-02 21:52 UTC, StephanieKirshner commented on src/components/EditDelete/EditDelete.jsx
> +import './style.js';
done

2021-09-02 21:53 UTC, StephanieKirshner commented on src/App.js
> +      <EditDelete />
oh okay, sorry. Thank you!

2021-09-03 14:43 UTC, jdickerson-banyan approved these changes

2021-09-03 14:43 UTC, merged