CC-15: converted style.css to styled components
Banyan-Labs/casestudy-cms pull request #16
Opened 2021-09-07 20:39 UTC by StephanieKirshner

Deleted style.css after converting it all to styled-components.

2021-09-08 20:37 UTC, jdickerson-banyan requested changes

2021-09-08 20:37 UTC, jdickerson-banyan commented on src/components/HomePage/HomePage.jsx
> +import { HomepageContainer } from './style';
Thank you for converting the file from css to styled components, but can you convert more of the style elements to styled components. At a minimum, please convert all the <div> elements in lines 24-42 into styled-components to make them more readable.

2021-09-08 21:14 UTC, StephanieKirshner commented
done

2021-09-09 15:21 UTC, jdickerson-banyan approved these changes

2021-09-09 15:21 UTC, merged