CC-20: converted all a tags to Link tags
Banyan-Labs/casestudy-cms pull request #19
Opened 2021-09-08 20:28 UTC by StephanieKirshner

2021-09-08 20:50 UTC, jdickerson-banyan requested changes

2021-09-08 20:50 UTC, jdickerson-banyan commented on src/components/DetailPage/DetailPage.jsx
> +        <Link href='#' id='edit'>
Links do not use hrefs. Instead, the structure is this:
`<Link to="/about">About</Link>`
or if you do not know the path you can use `to="#"`

2021-09-08 20:50 UTC, jdickerson-banyan commented on src/components/DetailPage/DetailPage.jsx
> +        <Link href='#' id='delete'>
to instead of href

2021-09-08 20:50 UTC, jdickerson-banyan commented on src/components/DetailPage/DetailPage.jsx
> +        <Link href='#' id='home'>
href

2021-09-08 21:17 UTC, StephanieKirshner commented on src/components/DetailPage/DetailPage.jsx
> +        <Link href='#' id='edit'>
done

2021-09-08 21:17 UTC, StephanieKirshner commented on src/components/DetailPage/DetailPage.jsx
> +        <Link href='#' id='delete'>
done

2021-09-08 21:18 UTC, StephanieKirshner commented on src/components/DetailPage/DetailPage.jsx
> +        <Link href='#' id='home'>
done

2021-09-09 15:35 UTC, jdickerson-banyan approved these changes

2021-09-09 15:36 UTC, merged