Cc 8
Banyan-Labs/casestudy-cms pull request #2
Opened 2021-08-31 15:51 UTC by StephanieKirshner

2021-08-31 17:06 UTC, jdickerson-banyan requested changes
Great job on this so far. Please complete the requested changes and take care of your merge conflicts.

2021-08-31 17:06 UTC, jdickerson-banyan commented on src/components/SignUpModal/SignInUpModal.jsx
> +import './style.js';
This is not necessary. Remove this line.

2021-08-31 17:06 UTC, jdickerson-banyan commented on src/components/SignUpModal/SignInUpModal.jsx
> +
remove the extra line

2021-08-31 17:06 UTC, jdickerson-banyan commented on src/setupTests.js
> +
why was this file modified?

2021-08-31 18:26 UTC, StephanieKirshner commented on README.md
> +Stephanie Cook -
fixed

2021-09-01 14:09 UTC, StephanieKirshner commented on src/App.js
> +import ReactDOM from 'react-dom';
done

2021-09-01 14:09 UTC, StephanieKirshner commented on src/App.js
> +
done

2021-09-01 14:10 UTC, StephanieKirshner commented on src/App.test.js
> +
I have no idea. I never touched this page

2021-09-01 14:10 UTC, StephanieKirshner commented on src/components/SignUpModal/index.jsx
> +
done

2021-09-01 14:10 UTC, StephanieKirshner commented on src/components/SignUpModal/SignInUpModal.jsx
> +import './style.js';
done

2021-09-01 14:10 UTC, StephanieKirshner commented on src/components/SignUpModal/SignInUpModal.jsx
> +
done

2021-09-01 14:18 UTC, jdickerson-banyan requested changes

2021-09-01 14:18 UTC, jdickerson-banyan commented on src/App.test.js
> +
This page is still showing pages when it shouldn't

2021-09-01 14:18 UTC, jdickerson-banyan commented on src/components/SignUpModal/SignInUpModal.jsx
> +export default SignUpModal;
add an blank line at the end of this file

2021-09-01 14:18 UTC, jdickerson-banyan commented on src/components/SignUpModal/style.js
> +import styled, { css } from 'styled-components';
what is the { css } doing here?

2021-09-01 14:18 UTC, jdickerson-banyan commented on src/components/SignUpModal/style.js
> +`;
add a blank line to the end of this file

2021-09-01 14:18 UTC, jdickerson-banyan commented on src/setupTests.js
> +
this file should not be changed

2021-09-01 15:35 UTC, StephanieKirshner commented on src/components/SignUpModal/SignInUpModal.jsx
> +export default SignUpModal;
done

2021-09-01 15:36 UTC, StephanieKirshner commented on src/components/SignUpModal/style.js
> +`;
done

2021-09-01 17:24 UTC, closed without merging